export const Followers = [
    {
      "login": "Filkolev",
      "id": 6649017,
      "node_id": "MDQ6VXNlcjY2NDkwMTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6649017?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Filkolev",
      "html_url": "https://github.com/Filkolev",
      "followers_url": "https://api.github.com/users/Filkolev/followers",
      "following_url": "https://api.github.com/users/Filkolev/following{/other_user}",
      "gists_url": "https://api.github.com/users/Filkolev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Filkolev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Filkolev/subscriptions",
      "organizations_url": "https://api.github.com/users/Filkolev/orgs",
      "repos_url": "https://api.github.com/users/Filkolev/repos",
      "events_url": "https://api.github.com/users/Filkolev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Filkolev/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Inspix",
      "id": 10298908,
      "node_id": "MDQ6VXNlcjEwMjk4OTA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/10298908?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Inspix",
      "html_url": "https://github.com/Inspix",
      "followers_url": "https://api.github.com/users/Inspix/followers",
      "following_url": "https://api.github.com/users/Inspix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Inspix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Inspix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Inspix/subscriptions",
      "organizations_url": "https://api.github.com/users/Inspix/orgs",
      "repos_url": "https://api.github.com/users/Inspix/repos",
      "events_url": "https://api.github.com/users/Inspix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Inspix/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "EBojilova",
      "id": 11708979,
      "node_id": "MDQ6VXNlcjExNzA4OTc5",
      "avatar_url": "https://avatars.githubusercontent.com/u/11708979?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EBojilova",
      "html_url": "https://github.com/EBojilova",
      "followers_url": "https://api.github.com/users/EBojilova/followers",
      "following_url": "https://api.github.com/users/EBojilova/following{/other_user}",
      "gists_url": "https://api.github.com/users/EBojilova/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EBojilova/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EBojilova/subscriptions",
      "organizations_url": "https://api.github.com/users/EBojilova/orgs",
      "repos_url": "https://api.github.com/users/EBojilova/repos",
      "events_url": "https://api.github.com/users/EBojilova/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EBojilova/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "AleksandarSt",
      "id": 3526110,
      "node_id": "MDQ6VXNlcjM1MjYxMTA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3526110?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AleksandarSt",
      "html_url": "https://github.com/AleksandarSt",
      "followers_url": "https://api.github.com/users/AleksandarSt/followers",
      "following_url": "https://api.github.com/users/AleksandarSt/following{/other_user}",
      "gists_url": "https://api.github.com/users/AleksandarSt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AleksandarSt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AleksandarSt/subscriptions",
      "organizations_url": "https://api.github.com/users/AleksandarSt/orgs",
      "repos_url": "https://api.github.com/users/AleksandarSt/repos",
      "events_url": "https://api.github.com/users/AleksandarSt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AleksandarSt/received_events",
      "type": "User",
      "site_admin": false
    }
  ]