export const userInfo = {
    "login": "dhristoskov",
    "id": 10851930,
    "node_id": "MDQ6VXNlcjEwODUxOTMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/10851930?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dhristoskov",
    "html_url": "https://github.com/dhristoskov",
    "followers_url": "https://api.github.com/users/dhristoskov/followers",
    "following_url": "https://api.github.com/users/dhristoskov/following{/other_user}",
    "gists_url": "https://api.github.com/users/dhristoskov/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dhristoskov/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dhristoskov/subscriptions",
    "organizations_url": "https://api.github.com/users/dhristoskov/orgs",
    "repos_url": "https://api.github.com/users/dhristoskov/repos",
    "events_url": "https://api.github.com/users/dhristoskov/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dhristoskov/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Dimitar Hristoskov",
    "company": null,
    "blog": "",
    "location": "Germany",
    "email": null,
    "hireable": true,
    "bio": null,
    "twitter_username": null,
    "public_repos": 24,
    "public_gists": 0,
    "followers": 4,
    "following": 3,
    "created_at": "2015-02-04T16:37:30Z",
    "updated_at": "2021-02-02T10:32:04Z"
  }